/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 asus_notebook.gltf --transform
Author: deonis (https://sketchfab.com/deonis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/asus-notebook-acde12c15de34befbe4dc0fd32489ab8
Title: Asus NoteBook
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/asus_notebook-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 59168.9, 65951.77]} rotation={[-Math.PI, 0, 0]}>
        <group position={[24212.05, -3405.4, 62534.47]}>
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.SubMtl2}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.asus_nout}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/asus_notebook-transformed.glb");
