/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 osaka_silla.gltf --transform
Author: HogarVenecia (https://sketchfab.com/HogarVenecia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/osaka-silla-c0016d2e14d54013b07e1517c053902a
Title: OSAKA SILLA
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/osaka_silla-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0.87]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.01, -0.01]} rotation={[-0.02, 0, 0]}>
            <mesh
              geometry={nodes.Object_10.geometry}
              material={materials.TELA}
            />
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.TELA}
            />
          </group>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.TELA}
            position={[0, -0.01, -0.01]}
            rotation={[-0.02, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.TELA}
            position={[0, -0.01, -0.01]}
            rotation={[-0.02, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.TELA}
            position={[0, -0.01, -0.01]}
            rotation={[-0.02, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials.BRIONI}
            position={[0, -0.01, -0.01]}
            rotation={[-0.02, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.BRIONI}
            position={[0.01, 0.43, 0.12]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_17.geometry}
            material={materials.BRIONI}
            position={[0.08, 0.43, 0.02]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_19.geometry}
            material={materials.BRIONI}
            position={[-0.07, 0.43, 0.02]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_21.geometry}
            material={materials.patas}
            position={[0, 0.11, 0]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_23.geometry}
            material={materials.material_0}
            position={[0, 0.43, 0.12]}
            rotation={[-Math.PI, 0, 0]}
            scale={0}
          />
          <mesh
            geometry={nodes.Object_25.geometry}
            material={materials.material_0}
            position={[-0.07, 0.43, 0.02]}
            rotation={[-Math.PI, 0, 0]}
            scale={0}
          />
          <mesh
            geometry={nodes.Object_27.geometry}
            material={materials.material_0}
            position={[0.08, 0.43, 0.02]}
            rotation={[-Math.PI, 0, 0]}
            scale={0}
          />
          <mesh
            geometry={nodes.Object_29.geometry}
            material={materials.BRIONI}
            position={[0, 0.11, 0]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_31.geometry}
            material={materials.BRIONI}
            position={[0, 0.11, 0]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_33.geometry}
            material={materials.BRIONI}
            position={[0, 0.11, 0]}
            scale={0.8}
          />
          <mesh
            geometry={nodes.Object_35.geometry}
            material={materials.BRIONI}
            position={[0, 0.11, 0]}
            scale={0.8}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/osaka_silla-transformed.glb");
